### ISSUE TITLE
Adding sex to the list of categories

### ISSUE THREAD

**Issue by corinna000** [ContributorCovenant/contributor_covenant#443] opened 2017-08-30 01:25 UTC
I added a PR for including sex in the list of categories. 

https://github.com/ContributorCovenant/contributor_covenant/pull/442

I believe the argument for including this is strong. Women are in the minority in technology, and there is an uphill battle on the inclusion of women in the field. In developing countries, women and girls are at even greater disadvantage, and it the root cause is discrimination based on sex. 

The current covenant has a callout for "sexual identity", however a glance at Wikipedia (https://en.wikipedia.org/wiki/Sexual_identity) makes a strong case that "sexual identity" is well established to mean conduct of sexual behavior, not actual sex. 

@CoralineAda asked whether essentialist arguments about sex are relevant to including this category. It seems that regardless of arguments of sex essentialism, discrimination on the basis of sex happens anyway, and is therefore a good candidate for adding to the existing list.

**Comment by mcantelon** [comment] 2017-08-30 03:20
:+1:

**Comment by drmike** [comment] 2017-09-26 21:38
I know this may sound silly to some but "gender" instead of "sex" may be a more friendly term to use.

And a friendly reminder that men are a target as well, not just women.  I'm a male victim of domestic violence.  Spent nearly six weeks in a coma because of it.

**Comment by corinna000** [comment] 2017-09-30 17:55
Gender is not a synonym for sex. The discrimination that women face is sex-based, not gender-based, and I'm proposing the covenant should be updated to reflect that reality.

**Comment by drmike** [comment] 2017-09-30 20:58
What I'm saying is that the text and wording should be neutral.

**Comment by winniequinn** [comment] 2017-11-09 14:30
This is a tough one. 

On one hand, I agree that sex-based discrimination (e.g. against intersex people, those capable of pregnancy, et cetera) is possible. On the other hand though, I agree with @drmike that gender is a more friendly term (as sex vs. gender is not always a pleasant concept for those who feel they have an incongruity there). I also disagree with @corinna000 that the discrimination women face is purely sex-based: On the contrary, I think it is often gender-based in practice (which is why trans women often suffer exactly the same sort of misogyny as cis women).

On balance, I feel it is better to not add sex to the list. It would effectively change the Covenant to say "you should not discriminate against those who present as women _as well those who were born as women_" and that just seems unpleasant me. (I am referring to "women" there just for sake of economy in language and consistency with the prior comments: The same applies to other sexes and genders as well, of course.)

I would, however, be okay with adding language for covering intersex people, those capable of pregnancy, and so on. Perhaps this is as simple as mentioning "sex characteristics" as opposed to "sex". This would possibly avoid the issues related to biological essentialism that @CoralineAda mentioned in #442 while still directly protecting against "sex-based discrimination". I admit this is maybe too technical, but I think "sex characteristics" would be more palatable than "sex" for transgender people in either case.

**Comment by TaylanUB** [comment] 2018-06-21 18:03
I wholeheartedly support adding "sex" to the list, in my opinion preferable over "gender" because:
- gender is presumably covered by "gender identity" which is already in the list,
- "gender" is a contentious term with different meanings to different people, for instance some feminists use the term to refer to the social *hierarchy* of "men over women" in sexist societies, or as a shorthand to "sex-based roles and stereotypes".

And without really wishing to sound too negative, I have to say that I'm deeply disappointed that this has not been one of the first categories to be added to the list.

Members of the female sex are one of the classes of people who have met the fiercest kinds of oppression for most of human history. Offences that have been and/or continue to be committed against them, usually for being female alone, include but are not limited to:
- Selective abortions
- Female infanticide
- Genital mutilation (FGM)
- Foot-binding (China)
- Menstruation-related ostracism (e.g. see "menstruation huts")
- Selling as property for domestic and sexual slavery
- Forced impregnation
- Control of reproductive choices (e.g. barring access to contraception and/or abortion)
- Imprisonment for miscarriage
- Characterization as inherently intellectually disabled
- Characterization as inherently morally fallible (see witch hunts)

I could not take this COC seriously if it decides to keep out sex from the list of protected categories simply because it makes another group feel uncomfortable. It would mean encoding misogyny right into the COC, in particular the erasure of sex-based female oppression, which would be completely unacceptable.

**Comment by TaylanUB** [comment] 2018-06-21 20:23
I thought maybe "gender (sex)" is the best way to word it. The word "gender" is perhaps more easily understood for some (some non-native speakers of English may think "sex" only refers to reproductive activity, since that definition is more popular), yet through the parantheses it's made clear that sex is meant and explicitly included.

Some die-hard proponents of the "sex does not equal gender" ideal (which I certainly sympathise with, mind you) may not like it, and should feel free to comment, but I think for the sake of being understood well, this is a good compromise. Words often have multiple meanings, after all.

Hence, an up-to-date pull request:

https://github.com/ContributorCovenant/contributor_covenant/pull/548

**Comment by CoralineAda** [comment] 2018-06-21 21:50
Gender and sex don’t mean the same thing, so I’m not comfortable with putting it in parentheses like that. 

I’m still engaged in discussion of whether ‘sex’ distinct from ‘gender’ is necessary and thinking pretty hard about it. My first instinct is that it’s cis-centric. Let’s hold off on a PR until I have a chance to get more input from the community.

**Comment by corinna000** [comment] 2018-06-21 22:08
I am trans, not cis, and am the originator of this change. Regardless of my being trans, I still would choose to have my sex protected as a separate characteristic, and believe that it’s especially important to acknowledge the various forms of discrimination that predominantly affect those whose sex is female. There is nothing “cis-centric” in acknowledging sex-based oppression. Trans-men are  susceptible to sex-based oppression regardless of their personal identity.

**Comment by nedbat** [comment] 2018-07-05 13:10
@CoralineAda I am a newcomer to these discussions, and so am probably missing many of the nuances of meaning here.  It seems to me that the goal of this list of categories is to ensure that everyone is included.  If someone comes here to say that they don't feel included until a category is added, isn't that a strong argument for adding it?  

I would think that for any given category, there are people for whom it doesn't apply, or could even be counter to their inclusion.  Perhaps I am too inexperienced in the forces at work here.

**Comment by kruug** [comment] 2018-09-18 00:54
@nedbat since diversity is superior to merit (per CoralineAda’s other repo), you don’t have to worry about being inexperienced.

**Closed** 2018-09-18 01:04 UTC
