### ISSUE TITLE
Ban CoralineAda from contributing for Violating the Code Of Conduct

### ISSUE THREAD

**Issue by SilicaAndPina** [ContributorCovenant/contributor_covenant#603] opened 2018-10-02 05:32 UTC
As you can see here. CoralineAda has gone out of there way to say very racist things towards White Males:
https://twitter.com/CoralineAda/status/1029162264979546112
This is a violation of the Code Of Conduct and thus they should be banned.

**Comment by david0178418** [comment] 2018-10-02 14:07
Seems to be a duplicate of #602.  Unfortunately, it has been locked, though (no surprises there).

**Comment by david0178418** [comment] 2018-10-02 14:16
Here are the archives of some of the hate posts that @SilicaAndPina  and @thedumbtechguy (in #602) pointed to:

https://web.archive.org/web/20181002140938/https:/twitter.com/CoralineAda/status/1029180145507164160
https://web.archive.org/web/20181002092946/https:/twitter.com/CoralineAda/status/1029162264979546112
https://web.archive.org/web/20180723025528/https:/twitter.com/CoralineAda/status/1021155466691457025
https://web.archive.org/web/20181002141224/https:/twitter.com/CoralineAda/status/1019017744212267008

**Closed** 2018-10-02 14:17 UTC
